version: '3.8'

services:
  app:
    build: .
    ports:
      - "${SERVER_PORT:-6000}:6000"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - DATABASE_NAME=${DATABASE_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION_HOURS=${JWT_EXPIRATION_HOURS}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=6000
      - STATIC_FILES_PATH=/app/static
      - LOG_LEVEL=${LOG_LEVEL}
      - LOG_FILE=${LOG_FILE}
      - LOG_FILE_SIZE=${LOG_FILE_SIZE}
      - LOG_FILE_COUNT=${LOG_FILE_COUNT}
      - DEFAULT_CARD_LENGTH=${DEFAULT_CARD_LENGTH}
    volumes:
      - logs:/app/logs
    restart: unless-stopped

volumes:
  logs: 